'use client';

import { useEffect, useMemo, useState } from 'react';
import { ArrowDownLeft, ArrowUpRight, Banknote, ChevronDown, CircleDollarSign, Cloud, Landmark, Lightbulb, Menu, Plus, PiggyBank, Sparkles, Target, Trash2, TrendingUp, WalletCards, X } from 'lucide-react';

type Account = { id: string; name: string; type: string; balance: number; color: string };
type Person = { id: string; name: string; initial: string; color: string; archived?: boolean };
type Transaction = { id: string; kind: 'income' | 'expense'; description: string; category: string; amount: number; personId: string; accountId: string; date: string };
type MoneyState = { accounts: Account[]; people: Person[]; transactions: Transaction[]; savingsGoal: number };

const starter: MoneyState = {
  accounts: [
    { id: 'checking', name: 'Everyday checking', type: 'Checking', balance: 6240, color: '#173f35' },
    { id: 'savings', name: 'Rainy day savings', type: 'Savings', balance: 12850, color: '#d99b62' },
    { id: 'cash', name: 'Household cash', type: 'Cash', balance: 420, color: '#879c85' },
  ],
  people: [
    { id: 'maya', name: 'Maya', initial: 'M', color: '#d77a55' },
    { id: 'noah', name: 'Noah', initial: 'N', color: '#567b70' },
  ],
  transactions: [
    { id: 't1', kind: 'income', description: 'Salary', category: 'Salary', amount: 4200, personId: 'maya', accountId: 'checking', date: '2026-08-28' },
    { id: 't2', kind: 'income', description: 'Weekend tips', category: 'Tips', amount: 385, personId: 'noah', accountId: 'checking', date: '2026-08-27' },
    { id: 't3', kind: 'expense', description: 'Green Market', category: 'Groceries', amount: 164.28, personId: 'maya', accountId: 'checking', date: '2026-08-26' },
    { id: 't4', kind: 'expense', description: 'Apartment rent', category: 'Housing', amount: 1850, personId: 'noah', accountId: 'checking', date: '2026-08-24' },
    { id: 't5', kind: 'expense', description: 'Metro passes', category: 'Transport', amount: 92, personId: 'maya', accountId: 'checking', date: '2026-08-22' },
    { id: 't6', kind: 'expense', description: 'Dinner with friends', category: 'Dining', amount: 78.5, personId: 'noah', accountId: 'cash', date: '2026-08-20' },
  ], savingsGoal: 3000,
};

const emptyHousehold: MoneyState = { accounts: [], people: [], transactions: [], savingsGoal: 0 };

const money = new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 });
const exactMoney = new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' });
const expenseCategories = ['Housing', 'Groceries', 'Dining', 'Transport', 'Utilities', 'Shopping', 'Health', 'Entertainment', 'Other'];
const incomeCategories = ['Salary', 'Tips', 'Freelance', 'Bonus', 'Benefits', 'Gift', 'Interest', 'Rental income', 'Other'];
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;
type CloudSession = { access_token: string; refresh_token?: string };

export default function Home() {
  const [data, setData] = useState<MoneyState>(emptyHousehold);
  const [ready, setReady] = useState(false);
  const [active, setActive] = useState<'overview' | 'transactions' | 'planning'>('overview');
  const [entryOpen, setEntryOpen] = useState(false);
  const [entryKind, setEntryKind] = useState<'income' | 'expense'>('expense');
  const [menuOpen, setMenuOpen] = useState(false);
  const [cloudSession, setCloudSession] = useState<CloudSession | null>(null);
  const [syncState, setSyncState] = useState<'local' | 'loading' | 'synced'>('local');
  const [signInOpen, setSignInOpen] = useState(false);
  const [setupOpen, setSetupOpen] = useState(false);
  const [welcomeName, setWelcomeName] = useState('');

  useEffect(() => {
    const saved = window.localStorage.getItem('hearth-money-v1'); if (saved) { try { setData(JSON.parse(saved) as MoneyState); } catch {} }
    let session = getCloudSession();
    if (window.location.hash.includes('access_token=')) {
      const params = new URLSearchParams(window.location.hash.slice(1)); const token = params.get('access_token');
      if (token) { session = { access_token: token, refresh_token: params.get('refresh_token') || undefined }; window.localStorage.setItem('hearth-cloud-session', JSON.stringify(session)); history.replaceState(null, '', window.location.pathname); }
    }
    if (session && SUPABASE_URL && SUPABASE_KEY) {
      setSyncState('loading');
      const connect = async () => {
        let activeSession = session!;
        if (activeSession.refresh_token) {
          try { activeSession = await refreshCloudSession(activeSession.refresh_token); window.localStorage.setItem('hearth-cloud-session', JSON.stringify(activeSession)); } catch {}
        }
        setCloudSession(activeSession);
        if (window.sessionStorage.getItem('hearth-welcome')) { setWelcomeName(userEmail(activeSession.access_token).split('@')[0]); window.sessionStorage.removeItem('hearth-welcome'); window.setTimeout(() => setWelcomeName(''), 4500); }
        const payload = await cloudLoad(activeSession);
        if (payload) setData(payload);
        else { setData(emptyHousehold); setSetupOpen(true); }
        setSyncState('synced'); setReady(true);
      };
      connect().catch(() => { setSyncState('local'); setReady(true); });
    } else setReady(true);
  }, []);
  useEffect(() => { if (ready) window.localStorage.setItem('hearth-money-v1', JSON.stringify(data)); }, [data, ready]);
  useEffect(() => { if (!ready || !cloudSession) return; const timer = window.setTimeout(() => { setSyncState('loading'); cloudSave(cloudSession, data).then(() => setSyncState('synced')).catch(() => setSyncState('local')); }, 900); return () => window.clearTimeout(timer); }, [data, ready, cloudSession]);

  const metrics = useMemo(() => {
    const totalBalance = data.accounts.reduce((sum, item) => sum + item.balance, 0);
    const income = data.transactions.filter((t) => t.kind === 'income').reduce((sum, t) => sum + t.amount, 0);
    const expenses = data.transactions.filter((t) => t.kind === 'expense').reduce((sum, t) => sum + t.amount, 0);
    const available = income - expenses;
    return { totalBalance, income, expenses, available, rate: income ? Math.max(0, (available / income) * 100) : 0 };
  }, [data]);
  const cashFlow = useMemo(() => {
    const now = new Date();
    return Array.from({ length: 6 }, (_, index) => {
      const month = new Date(now.getFullYear(), now.getMonth() - (5 - index), 1);
      const key = `${month.getFullYear()}-${String(month.getMonth() + 1).padStart(2, '0')}`;
      const entries = data.transactions.filter((transaction) => transaction.date.startsWith(key));
      return {
        key,
        label: month.toLocaleDateString('en-US', { month: 'short' }),
        income: entries.filter((entry) => entry.kind === 'income').reduce((sum, entry) => sum + entry.amount, 0),
        expenses: entries.filter((entry) => entry.kind === 'expense').reduce((sum, entry) => sum + entry.amount, 0),
      };
    });
  }, [data.transactions]);
  const maxCashFlow = Math.max(...cashFlow.flatMap((month) => [month.income, month.expenses]), 1);
  const activePeople = data.people.filter((person) => !person.archived);
  const personSpend = activePeople.map((person) => ({ ...person, amount: data.transactions.filter((t) => t.kind === 'expense' && t.personId === person.id).reduce((sum, t) => sum + t.amount, 0) }));
  const maxSpend = Math.max(...personSpend.map((p) => p.amount), 1);

  function submitEntry(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); const form = new FormData(event.currentTarget); const amount = Number(form.get('amount')); if (!amount || amount <= 0) return;
    const accountId = String(form.get('accountId'));
    const next: Transaction = { id: crypto.randomUUID(), kind: entryKind, amount, description: String(form.get('description')) || String(form.get('category')), category: String(form.get('category')), personId: String(form.get('personId')), accountId, date: String(form.get('date')) };
    setData((current) => ({ ...current, transactions: [next, ...current.transactions], accounts: current.accounts.map((a) => a.id === accountId ? { ...a, balance: a.balance + (entryKind === 'income' ? amount : -amount) } : a) })); setEntryOpen(false);
  }
  const tabs = [{ id: 'overview', label: 'Overview' }, { id: 'transactions', label: 'Transactions' }, { id: 'planning', label: 'Plan ahead' }] as const;

  return <main className="min-h-screen bg-background text-foreground">
    <header className="sticky top-0 z-30 border-b border-border/70 bg-background/90 backdrop-blur-xl"><div className="mx-auto flex h-16 max-w-[1440px] items-center gap-4 px-4 sm:px-7 lg:px-10">
      <button className="rounded-xl p-2 hover:bg-muted lg:hidden" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle menu"><Menu size={20}/></button>
      <div className="flex items-center gap-2.5"><span className="grid size-9 place-items-center rounded-xl bg-primary text-primary-foreground shadow-sm"><CircleDollarSign size={21}/></span><span className="font-display text-xl font-bold tracking-tight">Hearth</span></div>
      <div className="ml-auto flex items-center gap-2"><button onClick={() => setSignInOpen(true)} className="flex items-center gap-1.5 rounded-full bg-emerald-50 px-2.5 py-1.5 text-xs font-semibold text-emerald-800 sm:gap-2 sm:px-3" aria-label="Open cloud login"><Cloud size={14}/> {syncState === 'synced' ? 'Synced' : syncState === 'loading' ? 'Syncing…' : 'Local mode'}</button><button onClick={() => setSetupOpen(true)} className="hidden -space-x-2 sm:flex" aria-label={`Manage ${activePeople.length} household members`}>{activePeople.map((p) => <span key={p.id} className="grid size-8 place-items-center rounded-full border-2 border-background text-xs font-bold text-white" style={{ background: p.color }}>{p.initial}</span>)}{activePeople.length === 0 && <span className="inline-flex h-9 items-center gap-1.5 rounded-xl border border-border bg-card px-3 text-xs font-bold text-primary"><Plus size={14}/> Add member</span>}</button><button onClick={() => { setEntryKind('expense'); setEntryOpen(true); }} className="ml-1 hidden h-10 items-center gap-2 rounded-xl bg-primary sm:inline-flex px-4 text-sm font-bold text-primary-foreground shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><Plus size={17}/><span className="hidden sm:inline">Add entry</span></button></div>
    </div></header>
    <div className="mx-auto grid max-w-[1440px] lg:grid-cols-[220px_1fr]">
      <aside className={`${menuOpen ? 'block' : 'hidden'} border-b border-border bg-card p-4 lg:block lg:min-h-[calc(100vh-64px)] lg:border-b-0 lg:border-r lg:p-6`}><p className="mb-3 px-3 text-[11px] font-bold uppercase tracking-[.15em] text-muted-foreground">Household</p><nav className="space-y-1">{tabs.map((tab) => <button key={tab.id} onClick={() => { setActive(tab.id); setMenuOpen(false); }} className={`flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-semibold transition ${active === tab.id ? 'bg-primary text-primary-foreground shadow-sm' : 'text-muted-foreground hover:bg-muted hover:text-foreground'}`}>{tab.id === 'overview' ? <WalletCards size={18}/> : tab.id === 'transactions' ? <Banknote size={18}/> : <Target size={18}/>} {tab.label}</button>)}</nav><div className="my-6 h-px bg-border"/><p className="mb-3 px-3 text-[11px] font-bold uppercase tracking-[.15em] text-muted-foreground">Accounts</p><div className="space-y-1">{data.accounts.map((account) => <div key={account.id} className="flex items-center gap-3 rounded-xl px-3 py-2.5"><span className="size-2.5 rounded-full" style={{ background: account.color }}/><span className="min-w-0 flex-1 truncate text-sm font-medium">{account.name}</span><span className="text-xs font-bold tabular-nums">{money.format(account.balance)}</span></div>)}</div><button onClick={() => setSetupOpen(true)} className="mt-3 flex w-full items-center gap-2 px-3 text-sm font-semibold text-primary"><Plus size={15}/> Add account</button><div className="mt-8 rounded-2xl bg-[var(--sage-light)] p-4"><div className="mb-3 grid size-9 place-items-center rounded-xl bg-white/70 text-primary"><Sparkles size={18}/></div><p className="text-sm font-bold">A strong month</p><p className="mt-1 text-xs leading-relaxed text-muted-foreground">You kept {metrics.rate.toFixed(0)}% of income available for goals.</p></div></aside>
      <section className="min-w-0 px-4 pb-28 pt-7 sm:px-7 sm:py-7 lg:px-10 lg:py-9">
        {active === 'overview' && <><div className="mb-7 flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p className="mb-1 text-sm font-semibold text-muted-foreground">September overview</p><h1 className="font-display text-3xl font-bold tracking-tight sm:text-4xl">Your household, at a glance</h1></div><p className="max-w-sm text-sm leading-relaxed text-muted-foreground">Every account, contribution, and expense in one calm place.</p></div>
        <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Metric title="Across all accounts" value={money.format(metrics.totalBalance)} note="Opening balance today" icon={<Landmark/>} tone="dark"/><Metric title="Income this month" value={money.format(metrics.income)} note="Salary, tips & more" icon={<ArrowDownLeft/>} tone="green"/><Metric title="Spent this month" value={money.format(metrics.expenses)} note={`${data.transactions.filter(t => t.kind === 'expense').length} outgoing entries`} icon={<ArrowUpRight/>} tone="clay"/><Metric title="Available to plan" value={money.format(metrics.available)} note={`${metrics.rate.toFixed(0)}% savings rate`} icon={<PiggyBank/>} tone="gold"/></div>
        <div className="mt-5 grid gap-5 xl:grid-cols-[1.45fr_1fr]"><section className="panel p-5 sm:p-6"><div className="mb-6 flex items-start justify-between"><div><p className="eyebrow">Cash flow</p><h2 className="section-title">What came in, what went out</h2></div><button className="filter-button">Last 30 days <ChevronDown size={14}/></button></div><div className="chart-area" aria-label="Income and expense comparison chart">{cashFlow.map((month) => <div key={month.key} className="chart-group" title={`${month.label}: ${exactMoney.format(month.income)} income, ${exactMoney.format(month.expenses)} expenses`}><div className="chart-bar bg-[var(--sage)]" style={{height:`${(month.income/maxCashFlow)*100}%`}}/><div className="chart-bar bg-[var(--clay)]" style={{height:`${(month.expenses/maxCashFlow)*100}%`}}/><span>{month.label}</span></div>)}</div><div className="mt-5 flex gap-5 text-xs font-semibold text-muted-foreground"><span className="flex items-center gap-2"><i className="size-2 rounded-full bg-[var(--sage)]"/>Income</span><span className="flex items-center gap-2"><i className="size-2 rounded-full bg-[var(--clay)]"/>Expenses</span></div></section>
        <section className="panel p-5 sm:p-6"><div className="mb-6"><p className="eyebrow">By person</p><h2 className="section-title">Who paid this month</h2></div><div className="space-y-6">{personSpend.map((person) => <div key={person.id}><div className="mb-2 flex items-center gap-3"><span className="grid size-9 place-items-center rounded-full text-xs font-bold text-white" style={{background:person.color}}>{person.initial}</span><div className="flex-1"><p className="text-sm font-bold">{person.name}</p><p className="text-xs text-muted-foreground">{Math.round(person.amount/Math.max(metrics.expenses,1)*100)}% of household spend</p></div><strong className="text-sm tabular-nums">{money.format(person.amount)}</strong></div><div className="h-2 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full" style={{width:`${person.amount/maxSpend*100}%`,background:person.color}}/></div></div>)}</div><div className="mt-7 rounded-2xl border border-dashed border-[var(--sage)]/50 bg-[var(--sage-light)] p-4"><div className="flex gap-3"><Lightbulb className="mt-0.5 shrink-0 text-primary" size={19}/><div><p className="text-sm font-bold">Small saving opportunity</p><p className="mt-1 text-xs leading-relaxed text-muted-foreground">One home-cooked night each week could free up about <strong className="text-foreground">$120/month</strong>.</p></div></div></div></section></div>
        <div className="mt-5 grid gap-5 xl:grid-cols-[1.45fr_1fr]"><RecentTransactions transactions={data.transactions.slice(0,5)} people={data.people}/><section className="panel p-5 sm:p-6"><div className="mb-5 flex items-start justify-between"><div><p className="eyebrow">Goals</p><h2 className="section-title">Build the next chapter</h2></div><Target className="text-primary"/></div><div className="rounded-2xl bg-[var(--cream)] p-5"><div className="flex justify-between"><div><p className="text-sm font-bold">Emergency fund</p><p className="mt-1 text-xs text-muted-foreground">3 months of essentials</p></div><strong>{money.format(data.savingsGoal)}</strong></div><div className="mt-4 h-2.5 overflow-hidden rounded-full bg-white"><div className="h-full w-[68%] rounded-full bg-[var(--gold)]"/></div><p className="mt-2 text-right text-xs font-semibold text-muted-foreground">68% funded</p></div><button onClick={() => setActive('planning')} className="mt-4 flex w-full items-center justify-center gap-2 rounded-xl border border-border py-2.5 text-sm font-bold hover:bg-muted">View savings & investments <TrendingUp size={16}/></button></section></div></>}
        {active === 'transactions' && <TransactionsView data={data} onAdd={(kind) => {setEntryKind(kind);setEntryOpen(true)}}/>}{active === 'planning' && <PlanningView metrics={metrics}/>} 
      </section>
    </div>
    {welcomeName && <div role="status" className="fixed left-1/2 top-20 z-50 w-[calc(100%-2rem)] max-w-sm -translate-x-1/2 rounded-2xl border border-emerald-200 bg-card p-4 shadow-xl"><div className="flex items-start gap-3"><span className="grid size-9 shrink-0 place-items-center rounded-xl bg-[var(--sage-light)] text-primary"><Cloud size={18}/></span><div className="flex-1"><p className="font-display text-lg font-bold">Hi, {welcomeName}!</p><p className="text-xs text-muted-foreground">Welcome back. Your household is synced and ready.</p></div><button onClick={() => setWelcomeName('')} className="rounded-lg p-1 text-muted-foreground hover:bg-muted" aria-label="Dismiss welcome"><X size={16}/></button></div></div>}
    {entryOpen && <div className="fixed inset-0 z-50 grid place-items-end bg-black/25 backdrop-blur-sm sm:place-items-center sm:p-4" onMouseDown={(e)=>{if(e.target===e.currentTarget)setEntryOpen(false)}}><section className="w-full max-w-lg rounded-t-3xl bg-card p-5 shadow-2xl sm:rounded-3xl sm:p-7"><div className="mb-6 flex items-start justify-between"><div><p className="eyebrow">New entry</p><h2 className="font-display text-2xl font-bold">Add money {entryKind==='income'?'coming in':'going out'}</h2></div><button className="rounded-xl p-2 hover:bg-muted" onClick={()=>setEntryOpen(false)} aria-label="Close"><X size={20}/></button></div><div className="mb-5 grid grid-cols-2 rounded-xl bg-muted p-1"><button onClick={()=>setEntryKind('expense')} className={`rounded-lg py-2 text-sm font-bold ${entryKind==='expense'?'bg-card shadow-sm':'text-muted-foreground'}`}>Expense</button><button onClick={()=>setEntryKind('income')} className={`rounded-lg py-2 text-sm font-bold ${entryKind==='income'?'bg-card shadow-sm':'text-muted-foreground'}`}>Income</button></div><form onSubmit={submitEntry} className="grid gap-4 sm:grid-cols-2"><Field label="Amount"><input autoFocus required min="0.01" step="0.01" name="amount" type="number" placeholder="0.00"/></Field><Field label="Date"><input required name="date" type="date" defaultValue={new Date().toISOString().slice(0,10)}/></Field><Field label="Description"><input required name="description" placeholder={entryKind==='income'?'e.g. Weekend tips':'e.g. Grocery run'}/></Field><Field label="Category"><select name="category">{(entryKind==='income'?incomeCategories:expenseCategories).map(c=><option key={c}>{c}</option>)}</select></Field><Field label={entryKind==='income'?'Earned by':'Paid by'}><select name="personId">{entryKind === 'income' && <option value="joint">Joint household</option>}{activePeople.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></Field><Field label="Account"><select name="accountId">{data.accounts.map(a=><option value={a.id} key={a.id}>{a.name}</option>)}</select></Field><button className="mt-2 h-11 rounded-xl bg-primary font-bold text-primary-foreground sm:col-span-2">Save {entryKind}</button></form></section></div>}
    {signInOpen && <CloudDialog session={cloudSession} onClose={() => setSignInOpen(false)} onSignedOut={() => { window.localStorage.removeItem('hearth-cloud-session'); setCloudSession(null); setSyncState('local'); setSignInOpen(false); }} />}
    {setupOpen && <HouseholdDialog data={data} onChange={setData} onClose={() => setSetupOpen(false)} />}
    <nav className="fixed inset-x-3 bottom-3 z-40 grid grid-cols-3 gap-1 rounded-2xl border border-border/80 bg-card/95 p-1.5 shadow-2xl backdrop-blur-xl sm:hidden" aria-label="Quick money actions">
      <button onClick={() => setSetupOpen(true)} className="flex min-h-14 flex-col items-center justify-center gap-1 rounded-xl text-[11px] font-bold text-muted-foreground active:bg-muted"><WalletCards size={19}/><span>Household</span></button>
      <button onClick={() => { if (!data.accounts.length) setSetupOpen(true); else { setEntryKind('income'); setEntryOpen(true); } }} className="flex min-h-14 flex-col items-center justify-center gap-1 rounded-xl bg-[var(--sage-light)] text-[11px] font-bold text-primary active:opacity-70"><ArrowDownLeft size={20}/><span>Add income</span></button>
      <button onClick={() => { if (!data.accounts.length || !activePeople.length) setSetupOpen(true); else { setEntryKind('expense'); setEntryOpen(true); } }} className="flex min-h-14 flex-col items-center justify-center gap-1 rounded-xl bg-primary text-[11px] font-bold text-primary-foreground active:opacity-80"><ArrowUpRight size={20}/><span>Add expense</span></button>
    </nav>
  </main>;
}

function Metric({title,value,note,icon,tone}:{title:string;value:string;note:string;icon:React.ReactNode;tone:string}){return <article className={`metric-card metric-${tone}`}><div className="metric-icon">{icon}</div><p>{title}</p><strong>{value}</strong><span>{note}</span></article>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="form-field"><span>{label}</span>{children}</label>}
function RecentTransactions({transactions,people}:{transactions:Transaction[];people:Person[]}){return <section className="panel overflow-hidden"><div className="flex items-start justify-between p-5 pb-3 sm:p-6 sm:pb-3"><div><p className="eyebrow">Recent activity</p><h2 className="section-title">Latest household entries</h2></div><Banknote className="text-muted-foreground"/></div><div>{transactions.map(t=><div key={t.id} className="transaction-row"><span className={`transaction-icon ${t.kind}`}>{t.kind==='income'?<ArrowDownLeft/>:<ArrowUpRight/>}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">{t.description}</p><p className="text-xs text-muted-foreground">{t.category} · {t.personId === 'joint' ? 'Joint household' : people.find(p=>p.id===t.personId)?.name || 'Former member'}</p></div><div className="text-right"><p className={`text-sm font-bold tabular-nums ${t.kind==='income'?'text-emerald-700':''}`}>{t.kind==='income'?'+':'−'}{exactMoney.format(t.amount)}</p><p className="text-xs text-muted-foreground">{new Date(`${t.date}T12:00:00`).toLocaleDateString('en-US',{month:'short',day:'numeric'})}</p></div></div>)}</div></section>}
function TransactionsView({data,onAdd}:{data:MoneyState;onAdd:(kind:'income'|'expense')=>void}){return <><div className="mb-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="mb-1 text-sm font-semibold text-muted-foreground">Complete history</p><h1 className="font-display text-3xl font-bold sm:text-4xl">Money in motion</h1></div><div className="flex gap-2"><button onClick={()=>onAdd('income')} className="secondary-action"><ArrowDownLeft size={16}/>Add income</button><button onClick={()=>onAdd('expense')} className="primary-action"><Plus size={16}/>Add expense</button></div></div><RecentTransactions transactions={data.transactions} people={data.people}/></>}
function PlanningView({metrics}:{metrics:{available:number;rate:number}}){const monthlyInvest=Math.max(0,Math.round(metrics.available*.35));return <><div className="mb-7"><p className="mb-1 text-sm font-semibold text-muted-foreground">Savings & investing</p><h1 className="font-display text-3xl font-bold sm:text-4xl">Give every extra dollar a direction</h1></div><div className="grid gap-5 lg:grid-cols-3"><article className="panel p-6 lg:col-span-2"><div className="mb-7 flex items-start justify-between"><div><p className="eyebrow">Suggested monthly plan</p><h2 className="section-title">Based on your current cash flow</h2></div><Sparkles className="text-[var(--gold-dark)]"/></div><div className="space-y-5"><PlanRow label="Emergency savings" description="Build a 3-month safety net first" amount={Math.max(0,Math.round(metrics.available*.45))} color="#d99b62" percent={45}/><PlanRow label="Long-term investments" description="A diversified, low-cost portfolio" amount={monthlyInvest} color="#567b70" percent={35}/><PlanRow label="Short-term goals" description="Travel, home, or something meaningful" amount={Math.max(0,Math.round(metrics.available*.2))} color="#a3a98a" percent={20}/></div></article><article className="rounded-3xl bg-primary p-6 text-primary-foreground"><div className="grid size-11 place-items-center rounded-2xl bg-white/10"><TrendingUp/></div><p className="mt-8 text-sm text-white/65">Possible monthly investment</p><strong className="mt-2 block font-display text-4xl">{money.format(monthlyInvest)}</strong><p className="mt-4 text-sm leading-relaxed text-white/70">At a hypothetical 7% average return, this could grow to about <strong className="text-white">{money.format(monthlyInvest*173)}</strong> over 10 years.</p><p className="mt-7 text-[11px] leading-relaxed text-white/45">Illustration only, not financial advice. Investment returns are not guaranteed.</p></article></div></>}
function PlanRow({label,description,amount,color,percent}:{label:string;description:string;amount:number;color:string;percent:number}){return <div><div className="mb-2 flex items-center"><span className="mr-3 size-3 rounded-full" style={{background:color}}/><div className="flex-1"><p className="text-sm font-bold">{label}</p><p className="text-xs text-muted-foreground">{description}</p></div><strong>{money.format(amount)}</strong></div><div className="ml-6 h-2 rounded-full bg-muted"><div className="h-full rounded-full" style={{width:`${percent}%`,background:color}}/></div></div>}

function getCloudSession(): CloudSession | null { try { return JSON.parse(window.localStorage.getItem('hearth-cloud-session') || 'null') as CloudSession | null; } catch { return null; } }
function tokenPayload(token: string) { return JSON.parse(atob(token.split('.')[1].replace(/-/g, '+').replace(/_/g, '/'))) as { sub: string; email?: string }; }
function userId(token: string) { return tokenPayload(token).sub; }
function userEmail(token: string) { return tokenPayload(token).email || 'there'; }
async function cloudLoad(session: CloudSession): Promise<MoneyState | null> { const response = await fetch(`${SUPABASE_URL}/rest/v1/money_data?user_id=eq.${userId(session.access_token)}&select=payload`, { headers: { apikey: SUPABASE_KEY!, Authorization: `Bearer ${session.access_token}` } }); if (!response.ok) throw new Error('Sync failed'); const rows = await response.json() as { payload: MoneyState }[]; return rows[0]?.payload || null; }
async function refreshCloudSession(refreshToken: string): Promise<CloudSession> { const response = await fetch(`${SUPABASE_URL}/auth/v1/token?grant_type=refresh_token`, { method: 'POST', headers: { apikey: SUPABASE_KEY!, 'Content-Type': 'application/json' }, body: JSON.stringify({ refresh_token: refreshToken }) }); const result = await response.json(); if (!response.ok || !result.access_token) throw new Error('Session expired'); return { access_token: result.access_token, refresh_token: result.refresh_token || refreshToken }; }
async function cloudSave(session: CloudSession, payload: MoneyState) { const response = await fetch(`${SUPABASE_URL}/rest/v1/money_data?on_conflict=user_id`, { method: 'POST', headers: { apikey: SUPABASE_KEY!, Authorization: `Bearer ${session.access_token}`, 'Content-Type': 'application/json', Prefer: 'resolution=merge-duplicates' }, body: JSON.stringify({ user_id: userId(session.access_token), payload, updated_at: new Date().toISOString() }) }); if (!response.ok) throw new Error('Sync failed'); }
function CloudDialog({ session, onClose, onSignedOut }: { session: CloudSession | null; onClose: () => void; onSignedOut: () => void }) {
  const [mode, setMode] = useState<'login' | 'signup'>('login'); const [notice, setNotice] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  async function authenticate(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); setError(''); setNotice(''); setBusy(true);
    const form = new FormData(event.currentTarget); const email = String(form.get('email')).trim(); const password = String(form.get('password'));
    if (!SUPABASE_URL || !SUPABASE_KEY) { setError('Cloud sync is not configured yet.'); setBusy(false); return; }
    const endpoint = mode === 'login' ? `${SUPABASE_URL}/auth/v1/token?grant_type=password` : `${SUPABASE_URL}/auth/v1/signup`;
    try {
      const response = await fetch(endpoint, { method: 'POST', headers: { apikey: SUPABASE_KEY, 'Content-Type': 'application/json' }, body: JSON.stringify({ email, password }) });
      const result = await response.json();
      if (!response.ok) { setError(result.msg || result.error_description || result.message || result.error || 'Authentication failed.'); return; }
      if (result.access_token) {
        const nextSession = { access_token: result.access_token, refresh_token: result.refresh_token || undefined };
        window.localStorage.setItem('hearth-cloud-session', JSON.stringify(nextSession)); window.sessionStorage.setItem('hearth-welcome', '1'); window.location.reload();
      } else { setNotice('Account created. Check your email to confirm it, then return here and log in.'); setMode('login'); }
    } catch { setError('Could not reach Supabase. Check your connection and try again.'); } finally { setBusy(false); }
  }
  return <div className="fixed inset-0 z-[60] grid place-items-center bg-black/25 p-4 backdrop-blur-sm" onMouseDown={(e) => { if (e.target === e.currentTarget) onClose(); }}><section className="w-full max-w-md rounded-3xl bg-card p-7 shadow-2xl"><div className="flex items-start justify-between"><div className="grid size-11 place-items-center rounded-2xl bg-[var(--sage-light)] text-primary"><Cloud/></div><button onClick={onClose} className="rounded-xl p-2 hover:bg-muted" aria-label="Close"><X size={19}/></button></div><h2 className="mt-5 font-display text-2xl font-bold">{session ? 'Cloud account' : mode === 'login' ? 'Log in to Hearth' : 'Create your account'}</h2>{session ? <><p className="mt-2 text-sm leading-relaxed text-muted-foreground">Your household is synced. Use the same email and password to log in on any device.</p><button onClick={onSignedOut} className="secondary-action mt-6 w-full">Log out on this device</button></> : <><p className="mt-2 text-sm leading-relaxed text-muted-foreground">{mode === 'login' ? 'Access your household securely from any device.' : 'Create one account for your private household data.'}</p><div className="mt-5 grid grid-cols-2 rounded-xl bg-muted p-1"><button type="button" onClick={() => { setMode('login'); setError(''); }} className={`rounded-lg py-2 text-sm font-bold ${mode === 'login' ? 'bg-card shadow-sm' : 'text-muted-foreground'}`}>Log in</button><button type="button" onClick={() => { setMode('signup'); setError(''); }} className={`rounded-lg py-2 text-sm font-bold ${mode === 'signup' ? 'bg-card shadow-sm' : 'text-muted-foreground'}`}>Sign up</button></div><form onSubmit={authenticate} className="mt-5 space-y-3"><Field label="Email address"><input required autoComplete="email" name="email" type="email" placeholder="you@example.com"/></Field><Field label="Password"><input required minLength={6} autoComplete={mode === 'login' ? 'current-password' : 'new-password'} name="password" type="password" placeholder="At least 6 characters"/></Field>{notice && <p className="rounded-xl bg-[var(--sage-light)] p-3 text-xs font-semibold text-emerald-800">{notice}</p>}{error && <p className="text-xs font-semibold text-red-700">{error}</p>}<button disabled={busy} className="primary-action w-full disabled:opacity-60">{busy ? 'Please wait…' : mode === 'login' ? 'Log in' : 'Create account'}</button></form></>}</section></div>;
}

function HouseholdDialog({ data, onChange, onClose }: { data: MoneyState; onChange: React.Dispatch<React.SetStateAction<MoneyState>>; onClose: () => void }) {
  function addAccount(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const balance = Number(form.get('balance')) || 0; onChange((current) => ({ ...current, accounts: [...current.accounts, { id: crypto.randomUUID(), name: String(form.get('name')), type: String(form.get('type')), balance, color: ['#173f35','#d99b62','#879c85','#d77a55'][current.accounts.length % 4] }] })); event.currentTarget.reset(); }
  function addPerson(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const name = String(form.get('name')).trim(); if (!name) return; onChange((current) => ({ ...current, people: [...current.people, { id: crypto.randomUUID(), name, initial: name[0].toUpperCase(), color: ['#567b70','#d77a55','#9a682c','#68778d'][current.people.length % 4] }] })); event.currentTarget.reset(); }
  function removePerson(person: Person) { if (!window.confirm(`Remove ${person.name} from this household? Their past entries will be preserved.`)) return; onChange((current) => ({ ...current, people: current.people.map((item) => item.id === person.id ? { ...item, archived: true } : item) })); }
  return <div className="fixed inset-0 z-[60] grid place-items-center overflow-y-auto bg-black/25 p-4 backdrop-blur-sm"><section className="my-6 w-full max-w-2xl rounded-3xl bg-card p-6 shadow-2xl sm:p-8"><div className="flex items-start justify-between"><div><p className="eyebrow">Household setup</p><h2 className="font-display text-2xl font-bold">Accounts & people</h2><p className="mt-1 text-sm text-muted-foreground">Add as many accounts and household members as you need.</p></div><button onClick={onClose} className="rounded-xl p-2 hover:bg-muted"><X size={19}/></button></div><div className="mt-7 grid gap-7 md:grid-cols-2"><div><h3 className="mb-3 text-sm font-bold">Your accounts</h3><div className="mb-4 space-y-2">{data.accounts.map(a => <div key={a.id} className="flex items-center rounded-xl bg-muted/60 px-3 py-2"><span className="mr-2 size-2 rounded-full" style={{background:a.color}}/><span className="flex-1 truncate text-xs font-semibold">{a.name}</span><strong className="text-xs">{money.format(a.balance)}</strong></div>)}</div><form onSubmit={addAccount} className="space-y-3"><Field label="Account name"><input required name="name" placeholder="e.g. Joint checking"/></Field><div className="grid grid-cols-2 gap-3"><Field label="Type"><select name="type"><option>Checking</option><option>Savings</option><option>Cash</option><option>Credit card</option><option>Investment</option><option>Other</option></select></Field><Field label="Opening balance"><input required name="balance" type="number" step="0.01" placeholder="0.00"/></Field></div><button className="secondary-action w-full"><Plus size={15}/>Add account</button></form></div><div><h3 className="mb-3 text-sm font-bold">Household members</h3><div className="mb-4 space-y-2">{data.people.filter((p) => !p.archived).map(p => <div key={p.id} className="flex items-center gap-2 rounded-xl bg-muted px-3 py-2 text-xs font-bold"><i className="size-2 rounded-full" style={{background:p.color}}/><span className="flex-1">{p.name}</span><button type="button" onClick={() => removePerson(p)} className="rounded-lg p-1.5 text-muted-foreground hover:bg-red-50 hover:text-red-700" aria-label={`Remove ${p.name}`} title={`Remove ${p.name}`}><Trash2 size={14}/></button></div>)}</div><form onSubmit={addPerson} className="space-y-3"><Field label="Person's name"><input required name="name" placeholder="e.g. Alex"/></Field><button className="secondary-action w-full"><Plus size={15}/>Add person</button></form></div></div><button onClick={onClose} className="primary-action mt-8 w-full">Done</button></section></div>;
}

